#+STARTUP: content

* Drills
** Local variables                                                :awk:drill:

   How to declair local variables in a function?

*** Answer

    Local variables are declaired in the function arguments.

   #+BEGIN_SRC awk :results output code
     function f(      i){
         for (i = 0; i < 3; i++)
             print "bar's i=" i
     }
     function g(      i) { print i }
     END { f(); g() }
   #+END_SRC

** Current filename                                               :awk:drill:

   How do you get the current file name?

   :in-file ./text-files/access.log

*** Answer

    #+BEGIN_SRC awk :results output code :in-file ./text-files/access.log
      END { print FILENAME }
    #+END_SRC

** Current file row number                                        :awk:drill:

   How to get the current file row number?

   :in-file ./text-files/access.log

*** Answer

    #+BEGIN_SRC awk :results output code :in-file ./text-files/access.log
      { print FNR }
    #+END_SRC

** Number of fields in record                                     :awk:drill:

   How to get the number of fields in the current record?

   :in-file ./text-files/access.log

*** Answer

    NF is the variable.

    Example; print number of fields on each record.

    #+BEGIN_SRC awk :results output code :in-file ./text-files/access.log
      { print NF }
    #+END_SRC

** Read records variable                                          :awk:drill:

   What is the internal variable used to tell how many records have been read?

   :in-file ./text-files/access.log

*** Answer

    #+BEGIN_SRC awk :results output code :in-file ./text-files/access.log
      { print NR }
    #+END_SRC

** Empty line pattern                                             :awk:drill:

   How to skip empty lines?

   :in-file ./text-files/ledger.ledger

*** Answer

    #+BEGIN_SRC awk :results output code :in-file ./text-files/ledger.ledger
      NF { print }
    #+END_SRC

** Print line 7 to 10 of file                                     :awk:drill:

   How do you print line 7 to 10 with a range pattern?

   :in-file ./text-files/ledger.ledger

*** Answer

    #+BEGIN_SRC awk :results output code :in-file ./text-files/ledger.ledger
      FNR==7,FNR==10
    #+END_SRC

    #+RESULTS:
    #+begin_src awk
    2020-04-17 * Dustin. Köp av tangentbord.
        ;; ~/company/incomming-invoices/2020/2020-04-17-lenovo-keyboard-swedbank-transaction.pdf
        2:4:4:0                                   667.00 SEK
        2:0:1:8                                  -667.00 SEK
    #+end_src

** Skip lines starting with number                                :awk:drill:

   How do you skip a line that starts with a number?

   :in-file ./text-files/ledger.ledger

*** Answer

    #+BEGIN_SRC awk :results output code :in-file ./text-files/ledger.ledger
      $0 ~ /^[0-9]/ { next }
                    { print }
    #+END_SRC

** How many requests have each IP address done                    :awk:drill:

   Count the number of requests that each unique IP address have done.

   :in-file ./text-files/access.log

*** Answer

    The answer also contains some sorting.

    #+BEGIN_SRC awk :results output code :in-file ./text-files/access.log
      { counts[$1]+= 1}
      END { for (c in counts) { print c, counts[c] | "sort -r -k 2,2" }}
    #+END_SRC

** For loop                                                       :awk:drill:

   Write a for loop that print value 1 to 10

*** Answer

    #+BEGIN_SRC awk :results output code
      END { for (i=1; i <= 10; i++) { print i }}
    #+END_SRC

** The Structure of an AWK Program                                :awk:drill:

   Name the two most basic parts of an awk program.

*** Answer

    #+BEGIN_SRC awk :results output code
      pattern { action }
    #+END_SRC

** First fields equals to                                         :awk:drill:

   How to filter rows where first field is "129.204.106.181"?

*** Answer

    #+BEGIN_SRC awk :results output code :in-file ./text-files/access.log
      $1=="129.204.106.181" { print }
    #+END_SRC
