* Drills
** Local variables                                                :awk:drill:

   How to declair local variables in a function?

*** Answer

    Variable i is only local

   #+BEGIN_SRC awk :results output code
     function f(      i){
         for (i = 0; i < 3; i++)
             print "bar's i=" i
     }
     function g(      i) { print i }
     END { f(); g() }
   #+END_SRC

** Current filename                                               :awk:drill:

   How do you get the current file name?

*** Answer

    #+BEGIN_SRC awk :results output code :in-file ./awk.org
      END { print FILENAME }
    #+END_SRC

** Current file row number                                        :awk:drill:

   How to get the current file row number?

*** Answer

    Prints file row 1 to 5. FNR is the record number in current file.

    #+BEGIN_SRC awk :results output code :in-file ./awk.org
      FNR==1,FNR==5
    #+END_SRC

** Number of fields in record                                     :awk:drill:

   How to get the number of fields in the current record?

*** Answer

    NF is the variable.

    Example; print number of fields on each record.

    #+BEGIN_SRC awk :results output code :stdin ledger-text
      { print NF }
    #+END_SRC

** Read records variable                                          :awk:drill:

   What is the internal variable used to tell how many records have been read?

*** Answer

    #+BEGIN_SRC awk :results output code :stdin ledger-text
      { print NR }
    #+END_SRC

** Empty line pattern                                             :awk:drill:

   How to skip empty lines

*** Answer

    #+BEGIN_SRC awk :results output code :stdin ledger-text
      NF { print }
    #+END_SRC

** Print line 5 to 10 of file                                     :awk:drill:

   How do you print line 5 to 10 with a range pattern?

*** Answer

    #+BEGIN_SRC awk :results output code :stdin ledger-text
      FNR==5,FNR==10 { print FNR, $0 }
    #+END_SRC

** Skip lines starting with number                                :awk:drill:

   How do you skip a line that starts with a number?

*** Answer

    #+BEGIN_SRC awk :results output code :stdin ledger-text
      $0 ~ /^[0-9]/ { next }
                    { print }
    #+END_SRC
